### ISSUE TITLE
zend-servicemanager 3.x-dev is no longer immutable

### ISSUE THREAD

**Issue by Xerkus** [zendframework/zend-modulemanager#18]
develop branch needs to be updated to reflect reverted ServiceManager immutability: zendframework/zend-servicemanager#47

I will look into this first thing tomorrow morning unless someone does that first.

**Comment by weierophinney** [comment]
I'll be working on this this week; it requires changes to the module
manager as well.

**Comment by svycka** [comment]
can this be done faster? because every module written for zf2 requires this and it is impossible to go forward with zf3 compatibility

**Comment by weierophinney** [comment]
@svycka module manager and MVC have the largest number of deps, and we've had to push them to the end as a result. The good news is that we're down to the last few components; I'll be finishing up navigation today, which means I can start on these two finally. 

We're working as fast as we can; this stuff is not trivial, and we've had a number of issues crop up as we've pushed releases out that demonstrate how even one small oversight during migration can break an application. So, please be patient.
