### ISSUE TITLE
Check Documentation For Other Things

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-modulemanager#22]
# Check docs for other problems

> TLDR; Cast your eye over the documetation for any problems **not** covered in the other issues

Things slip through the net, so check the documentation for other problems that have been missed. Common other problems include

* Bullet lists (should be single ```*``` then space at the start of line)
* Inline code - should be marked by three backticks at start and finish
* ```bookdown.json``` file is correctly formated and has the right escaping
* Links between documentation using RST have been stripped
* Any other RST has been removed correctly
* Anything and everything not covered

If you end up fixing the same problem over and over, please ping [Gary Hockin](https://twitter.com/GeeH) - we may be able to add bespoke issue for that problem, or fix in automated capacity

**Comment by Xerkus** [comment]
As of now links were converted to markdown format but make no sense, eg `[The Module Autoloader](zend.loader.module-autoloader)`
Suggestion here is they have to be stripped, but may be they should be left in place and updated to link to actual components docs once those are migrated as well?

**Comment by GeeH** [comment]
I'm open @Xerkus - it will be a pita if we have to update these links later, so perhaps we can strip them, and then I'll open tickets once docs are rendered to add relevant hyperlinking (on all repositories)?

**Comment by froschdesign** [comment]
Fixed with #25
