### ISSUE TITLE
Check Documentation Tables

### ISSUE THREAD

**Issue by GeeH** [zendframework/zend-modulemanager#23]
# Check the tables in a document

> TLDR; All tables should be in the format of GHFM using ```|``` and ```-``` as horizontal and vertical separators respectively

Check all tables are in the correct format. Please don't use leading and trailing ```|``` - more information on github flavoured markdown tables can be found [here](https://help.github.com/articles/github-flavored-markdown/#tables).

**Comment by Xerkus** [comment]
GFM tables are rather limited. I think they should be used for the simplest tables only.
Big embedded tables in html are easier to read and edit since they have no one row  - one line limitation

**Comment by GeeH** [comment]
This issues isn't open for debate, it's open to get the tasks done.

**Comment by froschdesign** [comment]
Fixed with #25
