### ISSUE TITLE
Issue with allow_override config param after 2.7.1 release

### ISSUE THREAD

**Issue by mgazdzik** [zendframework/zend-modulemanager#34]
Hi there,

   I'd like to ask about possible regression in how modulemanager acts after latest release.
Previously it was possible to set `'allow_override' => true` in module configuration to make config globally overwriteable (useful for ex. in tests or few listeners where it was needed to switch service on the fly). However after those changes https://github.com/zendframework/zend-modulemanager/pull/31/files it's no more possible for any module to change allow_override parameter, and it's required to explicitly enable overrides in code and switch back to previous value afterwards.

My question is: was this on purpose? Do you recognize this merely as a bug allowing 'dirty' usage that was fixed, or a valid use case that could be restored?

Please let me know if I can provide any further insight into this issue.

Cheers,
Michał

**Comment by Xerkus** [comment]
I would say modules depending on override enabled must enable it explicitly as override mechanics itself is a hack.

**Comment by mgazdzik** [comment]
@Xerkus - thanks for response. I guess you're right, so what I've reported is not a bug nor regression.
However maybe it could be announced as security issue being fixed explicitly, so other developers have a referrence in future if they get hit by the same thing?

Anyway I'm closing issue as nothing more to do here - thanks for clarification!
