### ISSUE TITLE
 Could not find a valid ServiceManager for RoutePluginManager

### ISSUE THREAD

**Issue by visitek** [zendframework/zend-modulemanager#42]
After update zend-mvc from v2 to v3.

Fatal Error: Uncaught Zend\ModuleManager\Listener\Exception\RuntimeException: Could not find a valid ServiceManager for RoutePluginManager in /vendor/zendframework/zend-modulemanager/src/Listener/ServiceListener.php:202
Stack trace:
#0 /vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\ModuleManager\Listener\ServiceListener->onLoadModulesPost(Object(Zend\ModuleManager\ModuleEvent))
#1 /vendor/zendframework/zend-eventmanager/src/EventManager.php(143): Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEvent))
#2 /vendor/zendframework/zend-modulemanager/src/ModuleManager.php(129): Zend\EventManager\EventManager->triggerEvent(Object(Zend\ModuleManager\ModuleEvent))
#3 /vendor/zendframework/zend-mvc/src/Application.php(264): Zend\ModuleManager\ModuleManager->loadModules in /vendor/zendframework/zend-modulemanager/src/Listener/ServiceListener.php:202

**Comment by visitek** [comment]
hmm router is as module now

**Comment by mrowley-mf** [comment]
@visitek Did you find a solution to this issue? Thanks

**Comment by visitek** [comment]
add Zend\Router into config under modules

**Comment by weierophinney** [comment]
@mrowley-mf See the response from @visitek : all components with MVC integrations now also expose a `Module` class. Add `Zend\Router` to the top of your module list, and you'll get the functionality working.

Hint: if you use zend-component-installer, it will prompt you on first install. :smile:

**Comment by Philio** [comment]
I have the same issue when disabling development mode for an Apigility API following upgrade to the latest version, it works fine in dev mode and I have `Zend\Router` in my modules list. Any suggestions?

**Comment by weierophinney** [comment]
Is there a stale config cache, by any chance? (Look in data/cache/) if so,
and that corrects the issue, phrase report back, as it would need
indicative of a bug in the development mode transitions (they should clear
it).

**Comment by Philio** [comment]
Didn't think to check that as was trying to debug a crash from our staging server which clears the cache as part of the deployment.
Turns out the stale local cache was simply masking the real error.

Thanks for your help and quick reply!
