### ISSUE TITLE
Why none of the modules does not meet the recommended structure?

### ISSUE THREAD

**Issue by autowp** [zendframework/zend-modulemanager#52]
Why none of the Zend/* modules does not meet the [recommended structure](https://framework.zend.com/manual/2.4/en/modules/zend.module-manager.intro.html) 
 in part of Module.php, src/<module_namespace> and config files?

For example https://github.com/zendframework/zend-mail

**Comment by Ocramius** [comment]
The only requirement for a `Module` class is to be autoloaded. The initial positioning of the `Module.php` in `modules/ModuleName/Module.php` was a convention of the pre-composer era.

**Comment by autowp** [comment]
Ok. But my question is: why this structure is recommended and who recommends it not follow own recommendation?
Maybe change title to "One of possible structure"?

**Comment by froschdesign** [comment]
The documentation needs an update, because it describes the recommended structure of ZF2.

Btw. this is the current documentation: https://docs.zendframework.com/zend-modulemanager/intro/
