### ISSUE TITLE
Module "Generator" causes fatal error after update to zend-module-manager 2.8.0

### ISSUE THREAD

**Issue by KiwiJuicer** [zendframework/zend-modulemanager#72]
After a general composer update my application just broke with following error: 

> Fatal error: Uncaught Error: The "Generator" class is reserved for internal use and cannot be manually instantiated...

After looking up the breaking change I noticed these new lines in the `ModuleResolverListener`:

https://github.com/zendframework/zend-modulemanager/blob/c2c5b52ad9741e0b9a9c01a0ee72ab63e5b494b9/src/Listener/ModuleResolverListener.php#L27-L29

It was all working before. Do I now have to rename my module or is there a way to fix this behaviour?

**Comment by KiwiJuicer** [comment]
Quick work-around is to change the application.config.php entry from 'Generator' to Generator\Module::class

**Comment by akrabat** [comment]
Looks like this was caused by https://github.com/zendframework/zend-modulemanager/pull/5.

**Comment by Xerkus** [comment]
One possible fix is to change order to look for `$moduleName . '\Module'` first.

**Comment by weierophinney** [comment]
This is the second time in the past 2 months I've had #5 come up. I don't think anybody ever expected module names could conflict with reserved PHP classes...

We may have to revisit that to check for a namespace separator in the module name before attempting to see if the class exists; if no namespace separator is present, we should likely treat it as a namespace, and not a class.

Thoughts?

**Comment by weierophinney** [comment]
> One possible fix is to change order to look for $moduleName . '\Module' first.

That's the fallback lookup at this point. I'm not sure what impact it would make if we looked for that first; if somebody with an existing app that demonstrates the behavior would like to give it a try, I'd appreciate it.
