### ISSUE TITLE
fatol error

### ISSUE THREAD

**Issue by sufiyanpk7** [zendframework/zend-modulemanager#86]
Fatal error: Uncaught Zend_Cache_Exception: cache_dir "/opt/lampp/htdocs/magento2/var/cache/" is not writable in /opt/lampp/htdocs/magento2/vendor/magento/zendframework1/library/Zend/Cache.php:209 Stack trace: #0 /opt/lampp/htdocs/magento2/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/opt...') #1 /opt/lampp/htdocs/magento2/vendor/colinmollenhour/cache-backend-file/File.php(87): Zend_Cache_Backend_File->setCacheDir('/opt/lampp/htdo...') #2 /opt/lampp/htdocs/magento2/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array) #3 /opt/lampp/htdocs/magento2/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true) #4 /opt/lampp/htdocs/magento2/lib/internal/Magento/Framework/App/Cache/Frontend/Factory.php(156): Zend_Cache::factory('Magento\\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true) #5 /opt/lampp/htdocs/magento2/lib/internal/Magento/ in /opt/lampp/htdocs/magento2/vendor/magento/zendframework1/library/Zend/Cache.php on line 209

help

**Comment by FabianKoestring** [comment]
> Fatal error: Uncaught Zend_Cache_Exception: cache_dir "/opt/lampp/htdocs/magento2/var/cache/" is not writable in /opt/lampp/htdocs/magento2/vendor/magento/zendframework1/library/Zend/Cache.php:209 Stack trace: #0 /opt/lampp/htdocs/magento2/vendor/magento/zendframework1/library/Zend/Cache/Backend/File.php(180): Zend_Cache::throwException('cache_dir "/opt...') #1 /opt/lampp/htdocs/magento2/vendor/colinmollenhour/cache-backend-file/File.php(87): Zend_Cache_Backend_File->setCacheDir('/opt/lampp/htdo...') #2 /opt/lampp/htdocs/magento2/vendor/magento/zendframework1/library/Zend/Cache.php(153): Cm_Cache_Backend_File->__construct(Array) #3 /opt/lampp/htdocs/magento2/vendor/magento/zendframework1/library/Zend/Cache.php(94): Zend_Cache::_makeBackend('Cm_Cache_Backen...', Array, true, true) #4 /opt/lampp/htdocs/magento2/lib/internal/Magento/Framework/App/Cache/Frontend/Factory.php(156): Zend_Cache::factory('Magento\Framewo...', 'Cm_Cache_Backen...', Array, Array, true, true, true) #5 /opt/lampp/htdocs/magento2/lib/internal/Magento/ in /opt/lampp/htdocs/magento2/vendor/magento/zendframework1/library/Zend/Cache.php on line 209
> 
> help
> 
> ### Actual results

Seems like your permissions to that cache directory ('/opt/lampp/htdo...`) are wrong. You need to set write permissions.
