### ISSUE TITLE
List of modules

### ISSUE THREAD

**Issue by voltan** [zendframework/zend-modulemanager#92]
Hello
I search to find some modules for ZF3, but I couldn't find anything. is any list of modules available?

**Comment by michalbundyra** [comment]
@voltan Not sure if I understand you correctly...

Here you can find official Zend Framework components:
https://github.com/zendframework

and if you want to search for any packages you can use packagist:
https://packagist.org/?tags=module~zf2~zendframework~zend%20framework~zend%20framework%202~zf3~zf~zend

**Comment by weierophinney** [comment]
ZF2 modules should work fine for ZF3 in most instances - the majority of the changes we had were around the public API of the service manager and the event manager, and generally most modules targeting ZF2 still "just work". If they don't point them to the ZF3 migration docs so they can update. :)

Additionally, all Apigility modules (they're under the zfcampus organization) work with ZF3.

**Comment by voltan** [comment]
Thank you very much for your information
